### PR TITLE
possibility to use custom prime

### PR DESCRIPTION
**Pull request by prusnak**
In my calculations I'd like to use a custom prime (e.g. 2^256-189, see https://primes.utm.edu/lists/2small/ for the verbose list). This patch adds possibility to skip  `get_large_enough_prime` function call by defining a custom prime.

### CODE REVIEW

**Comment by mvonmaltitz** [comment]
This enhancement would easily allow making use of the homomorphic properties of Shamir's Secret Sharing scheme (e.g. adding constants to shared secrets or adding up different secrets). 
Therefore I would really like this pull request being merged.

**Comment by prusnak** [comment]
Rebased.

@shea256 What do you think?

**Comment by shea256** [comment]
@prusnak thank you for the improvement and please excuse the delay. Just merged in your change. Nice work :)

**Comment by prusnak** [comment]
Could you please release version with the patch included to PyPI? Thanks!

**Pull request merged**
